version: '3.8'

services:
  admin-module:
    build:
      context: ./admin-module
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # --- Основные ---
      - DATABASE_URL=postgresql+asyncpg://artstore:password@postgres:5432/admin_module
      - REDIS_HOST=redis
      # --- Аутентификация ---
      - AUTH_PROVIDERS=["local"] # В формате JSON: '["ldap", "local"]'
      # --- LDAP (пример) ---
      # - LDAP_SERVER_URL=ldap://ldap.example.com
      # - LDAP_BIND_DN=cn=admin,dc=example,dc=com
      # - LDAP_BIND_PASSWORD=ldap_password
      # - LDAP_USER_SEARCH_BASE=ou=users,dc=example,dc=com
      # - LDAP_GROUP_SEARCH_BASE=ou=groups,dc=example,dc=com
      # --- OAuth2 (пример для Google) ---
      # - OAUTH2_GOOGLE_CLIENT_ID=your-google-client-id
      # - OAUTH2_GOOGLE_CLIENT_SECRET=your-google-client-secret
    depends_on:
      - postgres
      - redis