"""initial_schema

Revision ID: 16c6973431df
Revises: 
Create Date: 2025-11-16 21:42:27.899130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16c6973431df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-increment ID записи'),
    sa.Column('file_id', sa.String(length=36), nullable=False, comment='UUID файла (FK к FileMetadata)'),
    sa.Column('bytes_transferred', sa.BigInteger(), nullable=False, comment='Количество переданных bytes'),
    sa.Column('download_time_ms', sa.Integer(), nullable=False, comment='Время скачивания в миллисекундах'),
    sa.Column('was_resumed', sa.Boolean(), nullable=False, comment='Было ли скачивание resumed (HTTP Range request)'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='Пользователь скачавший файл'),
    sa.Column('storage_element_id', sa.String(length=50), nullable=False, comment='ID Storage Element с которого скачан файл'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время скачивания'),
    sa.CheckConstraint('bytes_transferred >= 0', name='check_bytes_positive'),
    sa.CheckConstraint('download_time_ms >= 0', name='check_download_time_positive'),
    sa.PrimaryKeyConstraint('id'),
    comment='Статистика скачивания файлов для мониторинга и capacity planning'
    )
    op.create_index('idx_download_stats_file_created', 'download_statistics', ['file_id', 'created_at'], unique=False)
    op.create_index('idx_download_stats_storage_created', 'download_statistics', ['storage_element_id', 'created_at'], unique=False)
    op.create_index('idx_download_stats_username_created', 'download_statistics', ['username', 'created_at'], unique=False)
    op.create_index(op.f('ix_download_statistics_created_at'), 'download_statistics', ['created_at'], unique=False)
    op.create_index(op.f('ix_download_statistics_file_id'), 'download_statistics', ['file_id'], unique=False)
    op.create_index(op.f('ix_download_statistics_storage_element_id'), 'download_statistics', ['storage_element_id'], unique=False)
    op.create_index(op.f('ix_download_statistics_username'), 'download_statistics', ['username'], unique=False)
    op.create_table('file_metadata_cache',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID файла (совпадает с ID в Storage Element)'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='Оригинальное имя файла (для отображения пользователю)'),
    sa.Column('storage_filename', sa.String(length=512), nullable=False, comment='Имя файла в Storage Element (с username_timestamp_uuid)'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='Размер файла в bytes'),
    sa.Column('mime_type', sa.String(length=127), nullable=True, comment='MIME тип файла (image/jpeg, application/pdf, etc.)'),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False, comment='SHA256 хеш файла для верификации целостности'),
    sa.Column('username', sa.String(length=255), nullable=False, comment='Владелец файла (из JWT sub или username)'),
    sa.Column('tags', sa.ARRAY(sa.String(length=50)), nullable=True, comment='Теги файла для поиска (максимум 50 тегов)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание файла'),
    sa.Column('storage_element_id', sa.String(length=50), nullable=False, comment='ID Storage Element где хранится файл'),
    sa.Column('storage_element_url', sa.String(length=512), nullable=False, comment='URL Storage Element для скачивания файла'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания файла в Storage Element'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата последнего обновления метаданных'),
    sa.Column('cache_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата последнего обновления кеша'),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True, comment='Полнотекстовый поисковый вектор (auto-generated)'),
    sa.CheckConstraint('array_length(tags, 1) <= 50', name='check_tags_count'),
    sa.CheckConstraint('file_size >= 0', name='check_file_size_positive'),
    sa.PrimaryKeyConstraint('id'),
    comment='Кеш метаданных файлов для быстрого поиска и снижения нагрузки на Storage Elements'
    )
    op.create_index('idx_file_metadata_file_size', 'file_metadata_cache', ['file_size', 'created_at'], unique=False)
    op.create_index('idx_file_metadata_mime_type', 'file_metadata_cache', ['mime_type', 'created_at'], unique=False)
    op.create_index('idx_file_metadata_search_vector', 'file_metadata_cache', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_file_metadata_storage_elem', 'file_metadata_cache', ['storage_element_id', 'created_at'], unique=False)
    op.create_index('idx_file_metadata_tags', 'file_metadata_cache', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_file_metadata_username_created', 'file_metadata_cache', ['username', 'created_at'], unique=False)
    op.create_index(op.f('ix_file_metadata_cache_created_at'), 'file_metadata_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_file_metadata_cache_filename'), 'file_metadata_cache', ['filename'], unique=False)
    op.create_index(op.f('ix_file_metadata_cache_mime_type'), 'file_metadata_cache', ['mime_type'], unique=False)
    op.create_index(op.f('ix_file_metadata_cache_sha256_hash'), 'file_metadata_cache', ['sha256_hash'], unique=True)
    op.create_index(op.f('ix_file_metadata_cache_storage_element_id'), 'file_metadata_cache', ['storage_element_id'], unique=False)
    op.create_index(op.f('ix_file_metadata_cache_updated_at'), 'file_metadata_cache', ['updated_at'], unique=False)
    op.create_index(op.f('ix_file_metadata_cache_username'), 'file_metadata_cache', ['username'], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-increment ID записи'),
    sa.Column('query_text', sa.Text(), nullable=True, comment='Текст поискового запроса'),
    sa.Column('search_mode', sa.String(length=20), nullable=False, comment='Режим поиска (exact, partial, fulltext)'),
    sa.Column('filters_applied', sa.Text(), nullable=True, comment='Примененные фильтры (JSON строка)'),
    sa.Column('results_count', sa.Integer(), nullable=False, comment='Количество найденных результатов'),
    sa.Column('response_time_ms', sa.Integer(), nullable=False, comment='Время ответа в миллисекундах'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='Пользователь выполнивший поиск'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время выполнения поиска'),
    sa.CheckConstraint('response_time_ms >= 0', name='check_response_time_positive'),
    sa.CheckConstraint('results_count >= 0', name='check_results_count_positive'),
    sa.PrimaryKeyConstraint('id'),
    comment='История поисковых запросов для аналитики и оптимизации'
    )
    op.create_index('idx_search_history_created', 'search_history', ['created_at'], unique=False)
    op.create_index('idx_search_history_mode', 'search_history', ['search_mode', 'created_at'], unique=False)
    op.create_index('idx_search_history_username_created', 'search_history', ['username', 'created_at'], unique=False)
    op.create_index(op.f('ix_search_history_created_at'), 'search_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_history_username'), 'search_history', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_history_username'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_created_at'), table_name='search_history')
    op.drop_index('idx_search_history_username_created', table_name='search_history')
    op.drop_index('idx_search_history_mode', table_name='search_history')
    op.drop_index('idx_search_history_created', table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_file_metadata_cache_username'), table_name='file_metadata_cache')
    op.drop_index(op.f('ix_file_metadata_cache_updated_at'), table_name='file_metadata_cache')
    op.drop_index(op.f('ix_file_metadata_cache_storage_element_id'), table_name='file_metadata_cache')
    op.drop_index(op.f('ix_file_metadata_cache_sha256_hash'), table_name='file_metadata_cache')
    op.drop_index(op.f('ix_file_metadata_cache_mime_type'), table_name='file_metadata_cache')
    op.drop_index(op.f('ix_file_metadata_cache_filename'), table_name='file_metadata_cache')
    op.drop_index(op.f('ix_file_metadata_cache_created_at'), table_name='file_metadata_cache')
    op.drop_index('idx_file_metadata_username_created', table_name='file_metadata_cache')
    op.drop_index('idx_file_metadata_tags', table_name='file_metadata_cache', postgresql_using='gin')
    op.drop_index('idx_file_metadata_storage_elem', table_name='file_metadata_cache')
    op.drop_index('idx_file_metadata_search_vector', table_name='file_metadata_cache', postgresql_using='gin')
    op.drop_index('idx_file_metadata_mime_type', table_name='file_metadata_cache')
    op.drop_index('idx_file_metadata_file_size', table_name='file_metadata_cache')
    op.drop_table('file_metadata_cache')
    op.drop_index(op.f('ix_download_statistics_username'), table_name='download_statistics')
    op.drop_index(op.f('ix_download_statistics_storage_element_id'), table_name='download_statistics')
    op.drop_index(op.f('ix_download_statistics_file_id'), table_name='download_statistics')
    op.drop_index(op.f('ix_download_statistics_created_at'), table_name='download_statistics')
    op.drop_index('idx_download_stats_username_created', table_name='download_statistics')
    op.drop_index('idx_download_stats_storage_created', table_name='download_statistics')
    op.drop_index('idx_download_stats_file_created', table_name='download_statistics')
    op.drop_table('download_statistics')
    # ### end Alembic commands ###
