"""initial_schema

Revision ID: 4c7e84fcc6b9
Revises: 
Create Date: 2025-11-16 21:41:40.873808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c7e84fcc6b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jwt_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=36), nullable=False, comment='UUID version identifier'),
    sa.Column('private_key', sa.Text(), nullable=False, comment='RSA private key (PEM, 2048-bit)'),
    sa.Column('public_key', sa.Text(), nullable=False, comment='RSA public key (PEM, 2048-bit)'),
    sa.Column('algorithm', sa.String(length=10), nullable=False, comment='JWT signing algorithm'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Key creation timestamp'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Key expiration timestamp (25h grace period)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag'),
    sa.Column('rotation_count', sa.Integer(), nullable=False, comment='Rotation cycle counter'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jwt_keys_is_active'), 'jwt_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_jwt_keys_version'), 'jwt_keys', ['version'], unique=True)
    op.create_table('service_accounts',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Уникальный UUID идентификатор Service Account'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Человекочитаемое название Service Account'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Описание назначения Service Account'),
    sa.Column('client_id', sa.String(length=100), nullable=False, comment='Уникальный client_id для OAuth 2.0 (формат: sa_<environment>_<name>_<random>)'),
    sa.Column('client_secret_hash', sa.String(length=255), nullable=False, comment='Bcrypt хеш client_secret (минимум 32 символа)'),
    sa.Column('secret_history', sa.JSON(), nullable=True, comment='История предыдущих client_secret hashes для предотвращения reuse (максимум 5 хешей)'),
    sa.Column('secret_changed_at', sa.DateTime(timezone=True), nullable=False, comment='Дата последней смены client_secret (для password history tracking)'),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'AUDITOR', 'READONLY', name='service_account_role_enum'), nullable=False, comment='Роль Service Account в системе'),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'EXPIRED', 'DELETED', name='service_account_status_enum'), nullable=False, comment='Текущий статус Service Account'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='Флаг системного Service Account (не может быть удален)'),
    sa.Column('rate_limit', sa.Integer(), nullable=False, comment='Лимит запросов в минуту (default 100 req/min)'),
    sa.Column('secret_expires_at', sa.DateTime(timezone=True), nullable=False, comment='Дата истечения срока действия client_secret (автоматическая ротация каждые 90 дней)'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Дата и время последнего использования (последний успешный /api/auth/token)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время последнего обновления записи'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', name='uq_service_account_client_id'),
    sa.UniqueConstraint('name', name='uq_service_account_name')
    )
    op.create_index('idx_service_account_client_id', 'service_accounts', ['client_id'], unique=False)
    op.create_index('idx_service_account_secret_expiry', 'service_accounts', ['secret_expires_at'], unique=False)
    op.create_index('idx_service_account_status_role', 'service_accounts', ['status', 'role'], unique=False)
    op.create_index(op.f('ix_service_accounts_client_id'), 'service_accounts', ['client_id'], unique=True)
    op.create_index(op.f('ix_service_accounts_name'), 'service_accounts', ['name'], unique=True)
    op.create_index(op.f('ix_service_accounts_status'), 'service_accounts', ['status'], unique=False)
    op.create_table('storage_elements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Человекочитаемое имя storage element (уникальное)'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Описание хранилища'),
    sa.Column('mode', sa.Enum('EDIT', 'RW', 'RO', 'AR', name='storage_mode_enum'), nullable=False, comment='Режим работы storage element'),
    sa.Column('storage_type', sa.Enum('LOCAL', 'S3', name='storage_type_enum'), nullable=False, comment='Тип физического хранилища'),
    sa.Column('base_path', sa.String(length=500), nullable=False, comment='Базовый путь (local) или bucket name (s3)'),
    sa.Column('api_url', sa.String(length=255), nullable=False, comment='URL для API доступа к storage element'),
    sa.Column('api_key', sa.String(length=255), nullable=True, comment='API ключ для аутентификации (хешированный)'),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'DEGRADED', 'MAINTENANCE', name='storage_status_enum'), nullable=False, comment='Текущий статус storage element'),
    sa.Column('capacity_bytes', sa.BigInteger(), nullable=True, comment='Общая емкость в байтах'),
    sa.Column('used_bytes', sa.BigInteger(), nullable=False, comment='Использовано байтов'),
    sa.Column('file_count', sa.Integer(), nullable=False, comment='Количество файлов'),
    sa.Column('retention_days', sa.Integer(), nullable=True, comment='Срок хранения файлов в днях (None = бессрочно)'),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True, comment='Время последней проверки health'),
    sa.Column('is_replicated', sa.Boolean(), nullable=False, comment='Флаг репликации'),
    sa.Column('replica_count', sa.Integer(), nullable=False, comment='Количество реплик'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время последнего обновления записи'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_storage_mode_status', 'storage_elements', ['mode', 'status'], unique=False)
    op.create_index('idx_storage_status', 'storage_elements', ['status'], unique=False)
    op.create_index(op.f('ix_storage_elements_mode'), 'storage_elements', ['mode'], unique=False)
    op.create_index(op.f('ix_storage_elements_name'), 'storage_elements', ['name'], unique=True)
    op.create_index(op.f('ix_storage_elements_status'), 'storage_elements', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Имя пользователя (уникальное)'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email адрес (уникальный)'),
    sa.Column('first_name', sa.String(length=100), nullable=True, comment='Имя'),
    sa.Column('last_name', sa.String(length=100), nullable=True, comment='Фамилия'),
    sa.Column('hashed_password', sa.String(length=255), nullable=True, comment='Хеш пароля для локальной аутентификации'),
    sa.Column('ldap_dn', sa.String(length=500), nullable=True, comment='DEPRECATED: Поле не используется после Sprint 13 (LDAP removal)'),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'USER', name='user_role_enum'), nullable=False, comment='Роль пользователя в системе'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'LOCKED', 'DELETED', name='user_status_enum'), nullable=False, comment='Текущий статус пользователя'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='Флаг системного пользователя (не может быть удален или понижен)'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='Дата и время последнего входа'),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False, comment='Количество неудачных попыток входа'),
    sa.Column('lockout_until', sa.DateTime(timezone=True), nullable=True, comment='Дата и время до которой аккаунт заблокирован'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время последнего обновления записи'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_email'),
    sa.UniqueConstraint('username', name='uq_username')
    )
    op.create_index('idx_user_ldap_lookup', 'users', ['ldap_dn'], unique=False, postgresql_where=sa.text('ldap_dn IS NOT NULL'))
    op.create_index('idx_user_status_role', 'users', ['status', 'role'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_ldap_dn'), 'users', ['ldap_dn'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Уникальный идентификатор audit log entry'),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='Тип security события'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='Severity level: debug, info, warning, error, critical'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='ID пользователя (NULL для system events)'),
    sa.Column('service_account_id', sa.UUID(), nullable=True, comment='ID service account (NULL для user events)'),
    sa.Column('actor_type', sa.String(length=20), nullable=False, comment='Тип актора: user, service_account, system'),
    sa.Column('resource_type', sa.String(length=50), nullable=True, comment='Тип ресурса: user, service_account, jwt_key, storage_element'),
    sa.Column('resource_id', sa.String(length=100), nullable=True, comment='ID затронутого ресурса'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='Действие: create, read, update, delete, rotate, login, logout'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP адрес клиента (IPv4 или IPv6)'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='User agent string'),
    sa.Column('request_id', sa.String(length=36), nullable=True, comment='Correlation ID для трассировки (OpenTelemetry trace_id)'),
    sa.Column('session_id', sa.String(length=100), nullable=True, comment='Session identifier для корреляции событий'),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Дополнительные данные события (JSON format)'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='Успешность операции'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Текст ошибки (если success=false)'),
    sa.Column('hmac_signature', sa.String(length=64), nullable=False, comment='HMAC-SHA256 signature для защиты от изменения'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp события'),
    sa.ForeignKeyConstraint(['service_account_id'], ['service_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_service_account_id'), 'audit_logs', ['service_account_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_severity'), 'audit_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_audit_logs_success'), 'audit_logs', ['success'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_success'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_severity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_service_account_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_ldap_dn'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_status_role', table_name='users')
    op.drop_index('idx_user_ldap_lookup', table_name='users', postgresql_where=sa.text('ldap_dn IS NOT NULL'))
    op.drop_table('users')
    op.drop_index(op.f('ix_storage_elements_status'), table_name='storage_elements')
    op.drop_index(op.f('ix_storage_elements_name'), table_name='storage_elements')
    op.drop_index(op.f('ix_storage_elements_mode'), table_name='storage_elements')
    op.drop_index('idx_storage_status', table_name='storage_elements')
    op.drop_index('idx_storage_mode_status', table_name='storage_elements')
    op.drop_table('storage_elements')
    op.drop_index(op.f('ix_service_accounts_status'), table_name='service_accounts')
    op.drop_index(op.f('ix_service_accounts_name'), table_name='service_accounts')
    op.drop_index(op.f('ix_service_accounts_client_id'), table_name='service_accounts')
    op.drop_index('idx_service_account_status_role', table_name='service_accounts')
    op.drop_index('idx_service_account_secret_expiry', table_name='service_accounts')
    op.drop_index('idx_service_account_client_id', table_name='service_accounts')
    op.drop_table('service_accounts')
    op.drop_index(op.f('ix_jwt_keys_version'), table_name='jwt_keys')
    op.drop_index(op.f('ix_jwt_keys_is_active'), table_name='jwt_keys')
    op.drop_table('jwt_keys')
    # Drop ENUM types
    sa.Enum(name='user_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='user_role_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='storage_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='storage_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='storage_mode_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='service_account_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='service_account_role_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
