"""initial_schema_users_and_storage_elements

Revision ID: 0df874976374
Revises: 
Create Date: 2025-11-09 21:39:17.028966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df874976374'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_elements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Человекочитаемое имя storage element (уникальное)'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Описание хранилища'),
    sa.Column('mode', sa.Enum('EDIT', 'RW', 'RO', 'AR', name='storage_mode_enum'), nullable=False, comment='Режим работы storage element'),
    sa.Column('storage_type', sa.Enum('LOCAL', 'S3', name='storage_type_enum'), nullable=False, comment='Тип физического хранилища'),
    sa.Column('base_path', sa.String(length=500), nullable=False, comment='Базовый путь (local) или bucket name (s3)'),
    sa.Column('api_url', sa.String(length=255), nullable=False, comment='URL для API доступа к storage element'),
    sa.Column('api_key', sa.String(length=255), nullable=True, comment='API ключ для аутентификации (хешированный)'),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'DEGRADED', 'MAINTENANCE', name='storage_status_enum'), nullable=False, comment='Текущий статус storage element'),
    sa.Column('capacity_bytes', sa.BigInteger(), nullable=True, comment='Общая емкость в байтах'),
    sa.Column('used_bytes', sa.BigInteger(), nullable=False, comment='Использовано байтов'),
    sa.Column('file_count', sa.Integer(), nullable=False, comment='Количество файлов'),
    sa.Column('retention_days', sa.Integer(), nullable=True, comment='Срок хранения файлов в днях (None = бессрочно)'),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True, comment='Время последней проверки health'),
    sa.Column('is_replicated', sa.Boolean(), nullable=False, comment='Флаг репликации'),
    sa.Column('replica_count', sa.Integer(), nullable=False, comment='Количество реплик'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время последнего обновления записи'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_storage_mode_status', 'storage_elements', ['mode', 'status'], unique=False)
    op.create_index('idx_storage_status', 'storage_elements', ['status'], unique=False)
    op.create_index(op.f('ix_storage_elements_mode'), 'storage_elements', ['mode'], unique=False)
    op.create_index(op.f('ix_storage_elements_name'), 'storage_elements', ['name'], unique=True)
    op.create_index(op.f('ix_storage_elements_status'), 'storage_elements', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Имя пользователя (уникальное)'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email адрес (уникальный)'),
    sa.Column('first_name', sa.String(length=100), nullable=True, comment='Имя'),
    sa.Column('last_name', sa.String(length=100), nullable=True, comment='Фамилия'),
    sa.Column('hashed_password', sa.String(length=255), nullable=True, comment='Хеш пароля для локальной аутентификации (None для LDAP)'),
    sa.Column('ldap_dn', sa.String(length=500), nullable=True, comment='Distinguished Name в LDAP (None для локальных пользователей)'),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'USER', name='user_role_enum'), nullable=False, comment='Роль пользователя в системе'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'LOCKED', 'DELETED', name='user_status_enum'), nullable=False, comment='Текущий статус пользователя'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='Флаг системного пользователя (не может быть удален или понижен)'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='Дата и время последнего входа'),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False, comment='Количество неудачных попыток входа'),
    sa.Column('lockout_until', sa.DateTime(timezone=True), nullable=True, comment='Дата и время до которой аккаунт заблокирован'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время последнего обновления записи'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_email'),
    sa.UniqueConstraint('username', name='uq_username')
    )
    op.create_index('idx_user_ldap_lookup', 'users', ['ldap_dn'], unique=False, postgresql_where=sa.text('ldap_dn IS NOT NULL'))
    op.create_index('idx_user_status_role', 'users', ['status', 'role'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_ldap_dn'), 'users', ['ldap_dn'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_ldap_dn'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_status_role', table_name='users')
    op.drop_index('idx_user_ldap_lookup', table_name='users', postgresql_where=sa.text('ldap_dn IS NOT NULL'))
    op.drop_table('users')
    op.drop_index(op.f('ix_storage_elements_status'), table_name='storage_elements')
    op.drop_index(op.f('ix_storage_elements_name'), table_name='storage_elements')
    op.drop_index(op.f('ix_storage_elements_mode'), table_name='storage_elements')
    op.drop_index('idx_storage_status', table_name='storage_elements')
    op.drop_index('idx_storage_mode_status', table_name='storage_elements')
    op.drop_table('storage_elements')
    # ### end Alembic commands ###
