"""initial_schema

Revision ID: 100779395dad
Revises: 
Create Date: 2025-11-16 18:38:08.497038+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '100779395dad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_elem_01_config',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key (всегда 1 для singleton)'),
    sa.Column('current_mode', sa.String(length=10), nullable=False, comment='Текущий режим работы (edit/rw/ro/ar)'),
    sa.Column('mode_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время последнего изменения режима'),
    sa.Column('mode_changed_by', sa.String(length=255), nullable=True, comment='User ID кто изменил режим'),
    sa.Column('is_master', sa.Boolean(), nullable=False, comment='Текущий узел является мастером'),
    sa.Column('master_elected_at', sa.DateTime(timezone=True), nullable=True, comment='Время выбора текущего мастера'),
    sa.Column('total_files', sa.Integer(), nullable=False, comment='Количество файлов в хранилище'),
    sa.Column('total_size_bytes', sa.Integer(), nullable=False, comment='Общий размер файлов в байтах'),
    sa.Column('last_cache_rebuild', sa.DateTime(timezone=True), nullable=True, comment='Время последней пересборки кеша'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время последнего обновления'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_elem_01_files',
    sa.Column('file_id', sa.UUID(), nullable=False, comment='Уникальный идентификатор файла'),
    sa.Column('original_filename', sa.String(length=500), nullable=False, comment='Оригинальное имя файла'),
    sa.Column('storage_filename', sa.String(length=500), nullable=False, comment='Имя файла в хранилище (с username, timestamp, uuid)'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='Размер файла в байтах'),
    sa.Column('content_type', sa.String(length=255), nullable=False, comment='MIME type файла'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания файла'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время последнего обновления метаданных'),
    sa.Column('created_by_id', sa.String(length=255), nullable=False, comment='User ID создателя файла'),
    sa.Column('created_by_username', sa.String(length=255), nullable=False, comment='Username создателя'),
    sa.Column('created_by_fullname', sa.String(length=500), nullable=True, comment='ФИО создателя (опционально)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание содержимого файла'),
    sa.Column('version', sa.String(length=50), nullable=True, comment='Версия документа'),
    sa.Column('storage_path', sa.String(length=1000), nullable=False, comment='Относительный путь в хранилище (year/month/day/hour/)'),
    sa.Column('checksum', sa.String(length=64), nullable=False, comment='SHA256 checksum файла'),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True, comment='Full-text search vector (auto-generated)'),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Дополнительные метаданные (расширяемое поле)'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index('idx_storage_elem_01_filename', 'storage_elem_01_files', ['original_filename'], unique=False)
    op.create_index('idx_storage_elem_01_metadata', 'storage_elem_01_files', ['metadata_json'], unique=False, postgresql_using='gin')
    op.create_index('idx_storage_elem_01_search_vector', 'storage_elem_01_files', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_storage_elem_01_user_date', 'storage_elem_01_files', ['created_by_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_storage_elem_01_files_created_by_id'), 'storage_elem_01_files', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_storage_elem_01_files_created_by_username'), 'storage_elem_01_files', ['created_by_username'], unique=False)
    op.create_index(op.f('ix_storage_elem_01_files_file_id'), 'storage_elem_01_files', ['file_id'], unique=False)
    op.create_index(op.f('ix_storage_elem_01_files_original_filename'), 'storage_elem_01_files', ['original_filename'], unique=False)
    op.create_index(op.f('ix_storage_elem_01_files_storage_filename'), 'storage_elem_01_files', ['storage_filename'], unique=True)
    op.create_table('storage_elem_01_wal',
    sa.Column('transaction_id', sa.UUID(), nullable=False, comment='UUID транзакции'),
    sa.Column('operation_type', sa.String(length=50), nullable=False, comment='Тип операции (file_create, file_update, etc.)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Статус транзакции (pending, committed, rolled_back, failed)'),
    sa.Column('file_id', sa.UUID(), nullable=True, comment='UUID файла (для файловых операций)'),
    sa.Column('operation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Данные операции (файл, путь, метаданные и т.д.)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Сообщение об ошибке (если failed)'),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время начала операции'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Время завершения операции'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='Длительность операции в миллисекундах'),
    sa.Column('user_id', sa.String(length=255), nullable=True, comment='User ID инициатора операции'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index('idx_storage_elem_01_wal_data', 'storage_elem_01_wal', ['operation_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_storage_elem_01_wal_file', 'storage_elem_01_wal', ['file_id', 'started_at'], unique=False)
    op.create_index('idx_storage_elem_01_wal_status_time', 'storage_elem_01_wal', ['status', 'started_at'], unique=False)
    op.create_index(op.f('ix_storage_elem_01_wal_file_id'), 'storage_elem_01_wal', ['file_id'], unique=False)
    op.create_index(op.f('ix_storage_elem_01_wal_operation_type'), 'storage_elem_01_wal', ['operation_type'], unique=False)
    op.create_index(op.f('ix_storage_elem_01_wal_status'), 'storage_elem_01_wal', ['status'], unique=False)
    op.create_index(op.f('ix_storage_elem_01_wal_user_id'), 'storage_elem_01_wal', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_elem_01_wal_user_id'), table_name='storage_elem_01_wal')
    op.drop_index(op.f('ix_storage_elem_01_wal_status'), table_name='storage_elem_01_wal')
    op.drop_index(op.f('ix_storage_elem_01_wal_operation_type'), table_name='storage_elem_01_wal')
    op.drop_index(op.f('ix_storage_elem_01_wal_file_id'), table_name='storage_elem_01_wal')
    op.drop_index('idx_storage_elem_01_wal_status_time', table_name='storage_elem_01_wal')
    op.drop_index('idx_storage_elem_01_wal_file', table_name='storage_elem_01_wal')
    op.drop_index('idx_storage_elem_01_wal_data', table_name='storage_elem_01_wal', postgresql_using='gin')
    op.drop_table('storage_elem_01_wal')
    op.drop_index(op.f('ix_storage_elem_01_files_storage_filename'), table_name='storage_elem_01_files')
    op.drop_index(op.f('ix_storage_elem_01_files_original_filename'), table_name='storage_elem_01_files')
    op.drop_index(op.f('ix_storage_elem_01_files_file_id'), table_name='storage_elem_01_files')
    op.drop_index(op.f('ix_storage_elem_01_files_created_by_username'), table_name='storage_elem_01_files')
    op.drop_index(op.f('ix_storage_elem_01_files_created_by_id'), table_name='storage_elem_01_files')
    op.drop_index('idx_storage_elem_01_user_date', table_name='storage_elem_01_files')
    op.drop_index('idx_storage_elem_01_search_vector', table_name='storage_elem_01_files', postgresql_using='gin')
    op.drop_index('idx_storage_elem_01_metadata', table_name='storage_elem_01_files', postgresql_using='gin')
    op.drop_index('idx_storage_elem_01_filename', table_name='storage_elem_01_files')
    op.drop_table('storage_elem_01_files')
    op.drop_table('storage_elem_01_config')
    # ### end Alembic commands ###
