# Kubernetes Secrets для ArtStore Admin Module
#
# Этот манифест демонстрирует как хранить секретные данные в Kubernetes Secrets
# для использования в Admin Module через SecretProvider auto-detection.
#
# ВАЖНО: Secrets должны быть созданы в том же namespace где развертывается приложение.
#
# Создание секретов:
#   kubectl apply -f kubernetes-secrets.yaml -n artstore
#
# Просмотр секретов:
#   kubectl get secrets -n artstore
#   kubectl describe secret artstore-admin-secrets -n artstore
#
# ВАЖНО: НЕ коммитить этот файл с реальными секретами в Git!
# В production используйте:
# - Sealed Secrets (bitnami-labs/sealed-secrets)
# - External Secrets Operator
# - HashiCorp Vault
# - AWS Secrets Manager / Azure Key Vault / GCP Secret Manager

apiVersion: v1
kind: Secret
metadata:
  name: artstore-admin-secrets
  namespace: artstore
  labels:
    app: artstore
    component: admin-module
    managed-by: kubectl
type: Opaque

# stringData позволяет вводить секреты в plain text (автоматически кодируется в base64)
stringData:
  # Database credentials
  DB_PASSWORD: "secure-postgres-password-change-me"

  # Redis credentials
  REDIS_PASSWORD: "secure-redis-password-change-me"

  # HMAC Secret для audit logging (minimum 32 символа)
  SECURITY_AUDIT_HMAC_SECRET: "production-hmac-secret-minimum-32-characters-required-for-security"

  # JWT Keys - полное PEM содержимое (preferred для k8s)
  # Генерация ключей:
  #   openssl genrsa -out private_key.pem 2048
  #   openssl rsa -in private_key.pem -pubout -out public_key.pem

  JWT_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAwB9aAE7KgGdRzR5vRFWqC0WqNr7KXcJgU1nQ8Y7fD0RhD5mQ
    +vLJGJ0YQhPa2T7JpK3zK4TqWzYqQ+9ZwFvE0vX8E7gU1YHqY8B2CZ4L9jK1kQ7d
    ... (ЗАМЕНИТЕ НА РЕАЛЬНЫЙ ПРИВАТНЫЙ КЛЮЧ)
    dGaE4L0YQhPa2T7JpK3zK4TqWzYqQ+9ZwFvE0vX8E7gU1YHqY8B2CZ4L9jK1kQ==
    -----END RSA PRIVATE KEY-----

  JWT_PUBLIC_KEY: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwB9aAE7KgGdRzR5vRFWq
    C0WqNr7KXcJgU1nQ8Y7fD0RhD5mQ+vLJGJ0YQhPa2T7JpK3zK4TqWzYqQ+9ZwFvE
    ... (ЗАМЕНИТЕ НА РЕАЛЬНЫЙ ПУБЛИЧНЫЙ КЛЮЧ)
    0vX8E7gU1YHqY8B2CZ4L9jK1kQIDAQAB
    -----END PUBLIC KEY-----

---
# ConfigMap для non-sensitive конфигурации
# (опционально, можно использовать env vars напрямую в Deployment)
apiVersion: v1
kind: ConfigMap
metadata:
  name: artstore-admin-config
  namespace: artstore
  labels:
    app: artstore
    component: admin-module
data:
  APP_NAME: "ArtStore Admin Module"
  APP_VERSION: "0.1.0"
  APP_DEBUG: "false"
  ENVIRONMENT: "production"

  # Database settings (non-sensitive)
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_USERNAME: "artstore"
  DB_DATABASE: "artstore_admin"
  DB_POOL_SIZE: "20"
  DB_MAX_OVERFLOW: "40"

  # Redis settings (non-sensitive)
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_POOL_SIZE: "20"

  # JWT Settings
  JWT_ALGORITHM: "RS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: "7"
  JWT_KEY_ROTATION_HOURS: "24"

  # Security Settings (non-sensitive)
  SECURITY_AUDIT_RETENTION_DAYS: "2555"

  # CORS Settings
  CORS_ENABLED: "true"
  CORS_ALLOW_ORIGINS: '["https://artstore.example.com", "https://admin.artstore.example.com"]'
  CORS_ALLOW_CREDENTIALS: "true"

  # Logging
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"

  # Monitoring
  PROMETHEUS_ENABLED: "true"
  OPENTELEMETRY_ENABLED: "true"
  OPENTELEMETRY_SERVICE_NAME: "artstore-admin-module"
  OPENTELEMETRY_EXPORTER_ENDPOINT: "http://otel-collector:4317"

  # Service Discovery
  SERVICE_DISCOVERY_ENABLED: "true"
  SERVICE_DISCOVERY_REDIS_CHANNEL: "artstore:service_discovery"

  # Scheduler
  SCHEDULER_ENABLED: "true"
  SCHEDULER_JWT_ROTATION_ENABLED: "true"
  SCHEDULER_JWT_ROTATION_INTERVAL_HOURS: "24"
  SCHEDULER_TIMEZONE: "UTC"

  # Rate Limiting
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS_PER_MINUTE: "60"
  RATE_LIMIT_BURST: "10"

---
# Примечания:
#
# 1. Secret Auto-Detection:
#    SecretProvider автоматически обнаруживает Kubernetes окружение
#    по наличию файла /var/run/secrets/kubernetes.io/serviceaccount/token
#
# 2. Secret Mounting:
#    Secrets монтируются как файлы в /var/run/secrets/artstore/
#    Имя файла = имя ключа в Secret (например: SECURITY_AUDIT_HMAC_SECRET)
#
# 3. Fallback Chain:
#    k8s Secret → Environment Variable → File-based → Default
#
# 4. Security Best Practices:
#    - Используйте RBAC для ограничения доступа к Secrets
#    - Включите encryption at rest для etcd (--encryption-provider-config)
#    - Регулярно ротируйте секреты (используйте External Secrets Operator)
#    - Не храните Secrets в Git (используйте Sealed Secrets или подобное)
#
# 5. Ротация секретов:
#    kubectl create secret generic artstore-admin-secrets-v2 \
#      --from-file=SECURITY_AUDIT_HMAC_SECRET=./new-hmac-secret \
#      --dry-run=client -o yaml | kubectl apply -f -
#
#    # Обновите Deployment для использования нового Secret
#    kubectl set env deployment/admin-module --from=secret/artstore-admin-secrets-v2
