issuer: http://localhost:5556/dex
storage:
  type: postgres
  config:
    host: postgres
    port: 5432
    user: artstore
    password: password
    dbname: dex
    ssl:
      mode: disable
web:
  http: 0.0.0.0:5556
grpc:
  http: 0.0.0.0:5557
telemetry:
  http: 0.0.0.0:5558

staticClients:
- id: artstore
  redirectURIs:
  - 'http://localhost/callback'
  name: "artstore"
  secret: "admin-ui-secret"

oauth2:
  passwordConnector: ldap
  responseTypes: ["code", "token", "id_token"]

connectors:
- type: ldap
  id: ldap
  name: LDAP
  config:
    host: ldap:3389
    insecureNoSSL: true
    startTLS: false

    bindDN: cn=Directory Manager
    bindPW: password
    usernamePrompt: LDAP Username

    userSearch:
      baseDN: ou=People,dc=artstore,dc=local
      filter: "(objectClass=person)"
      username: uid
      idAttr: uid
      emailAttr: mail
      nameAttr: cn
      preferredUsernameAttr: uid

    groupSearch:
      baseDN: ou=Groups,dc=artstore,dc=local
      filter: "(objectClass=groupOfUniqueNames)"
      userMatchers:
      - userAttr: dn
        groupAttr: uniqueMember

      # Represents group name.
      nameAttr: cn
