issuer: http://localhost:5556/dex
storage:
  type: postgres
  config:
    host: artstore_postgres
    port: 5432
    user: artstore
    password: password
    dbname: artstore
    ssl:
      mode: disable
web:
  http: 0.0.0.0:5556
grpc:
  http: 0.0.0.0:5557
telemetry:
  http: 0.0.0.0:5558

# Коннектор для статических пользователей.
# В реальном проекте здесь будет коннектор к LDAP, GitHub или другому провайдеру.
staticClients:
- id: admin-ui
  redirectURIs:
  - 'http://localhost/callback'
  name: 'Admin UI'
  secret: admin-ui-secret

connectors:
- type: mockCallback
  id: mock
  name: Mock Connector

staticPasswords:
- email: "admin@admin.com"
  # bcrypt hash for "password"
  hash: "$2a$10$2b2u8ZJ/u.R16jBfJIsQp.E/2OO1/O6lnP2l.d2/LHLsT.d6Lwy4y"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"